### ISSUE TITLE
[level-1] logical cloud deployment, bug or wrong configuration?

### ISSUE THREAD

**Issue by herrfox** [open-ness/EMCO#11]
Hello All,

I have a question regrading EMCO level-1 logical cloud configuration/deployment.  I have tried several time to deploy it with namespace "eit1" and level-1. I need it as the target namespace is always configured on my target k8s cluster.
The problem is that my configuration is not taken into account.
I know this because if I connect to mongo-db and check cloudconfig key in the DB ("key" : "{cluster,level,namespace,provider,}") it still contains level definition set to 0 and namespace definition set to default:
{ 
    "_id" : ObjectId("60742d10499f9e246826257f"), 
    "cluster" : "cluster1", 
    "level" : "0", 
    "namespace" : "deafult", 
    "provider" : "provider1", 
    "config" : {
        "config" : "YXBpVmV(.......)2c9PQo="
    }, 
    "key" : "{cluster,level,namespace,provider,}"
}
[logicalcloudcondig.txt](https://github.com/open-ness/EMCO/files/6297092/logicalcloudcondig.txt)

However the orchestartor DB configuration contains correct data:
{ 
    "_id" : ObjectId("60745026c1986d527c297386"), 
    "logical-cloud-name" : "lc1", 
    "project" : "proj1", 
    "key" : "{logical-cloud-name,project,}", 
    "logicalcloud" : {
        "metadata" : {
            "logicalcloudname" : "lc1", 
            "description" : "", 
            "userdata1" : "", 
            "userdata2" : ""
        }, 
        "specification" : {
            "namespace" : "eit1", 
            "level" : "1",

Of course the instantiation will fail as there will be no reference to cluster to deploy the app on it.
But when I edit those entries in MONGO DB, all instantiation, termination operations are running fine.

Is it something that I am missing in the configuration or it's a bug?
Any help is highly appreciated. If you need any logs etc. I can send it at will.

BTW. EMCO is a nice piece of SW. I love it :)

regards
Greg

**Comment by igordcard** [comment]
Hi Greg,

"I need it as the target namespace is always configured on my target k8s cluster."
A clarification question first: Do you mean that you already have a cluster named "eit1" on your cluster?

**Comment by herrfox** [comment]
Hello Igor,

Thank you for you answer. 
As for the issue.
The cluster that I use, as the target cluster for EMCO deployment, has already namespace defined (namespace: eit1) along with some specific k8s settings for this particular namespace (crds, sa, tn etc. which are static)

So to be precisse :
- "Do you mean that you already have a cluster named "eit1" on your cluster?"
- No.

It's about the cluster settings in the Mogo DB. They are not as defined in logical cluster definition yaml.

**Comment by igordcard** [comment]
Hi Greg,
It sounds like the namespace is indeed defined in the cluster (in the actual K8s deployment, outside of EMCO). If this is the case, there will be a clash with EMCO (which expects to fully manage the namespace in the cluster). It's possible that you may be able to further deploy the resources you need (crds, sa, tn, etc.) (after a successful L1 instantiation) via deployment intent groups on top of the L1 logical cloud, although I personally can't say for sure.

In terms of mongodb/cloudconfig, after a successful L1 LC instantiation you will still see the L0/default entry but there will also be an L1/eit1 entry (after the cluster approves a certificate signing request, requested by EMCO).

Can you try instantiating a L1 logical cloud without pointing to the existing "eit1" namespace just to double-check that you don't face the original issue?

**Comment by herrfox** [comment]
Hi,

I have checked the flow as you asked but the results is the same.

test scenario 1
- Logical cloud deployed with namespace: testns
- Logical cloud was succesfuly instatntited and the namespace "testns" was created on target k8s however the cloudconfig table in DB does not have it like you said. But of course there is level: 0 and namespace "deafult"
- Instantiation fials as EMCO can't find the proper cluster configuration when searchng for it in DB: "CloudConfig for this app will be looked up using level and namespace specified","namespace":"testns""

Below is a log from rsync
{"SOURCE":"file[appcontext.go:488] func[appcontext.(*AppContext).GetAppInstruction]","level":"info","msg":"Getting app instruction","s":"/context/1746572129129870541/app/instruction/order/","time":"2021-04-14T07}
{"SOURCE":"file[context.go:800] func[context.applyFnComApp]","appsorder":"{\"apporder\":[\"aic-pvc\",\"aic-intnet\",\"aic-vdu\"]}","level":"info","msg":"appsorder ","string":{"apporder":["aic-pvc","aic-intnet","}
{"SOURCE":"file[context.go:817] func[context.applyFnComApp]","fields.level":"1","level":"info","msg":"CloudConfig for this app will be looked up using level and namespace specified","namespace":"testns","time":"}
{".Cluster":"cluster1",".Level":"0",".Namespace":"",".Provider":"provider1","SOURCE":"file[connector.go:58] func[connector.GetKubeConfig]","level":"info","msg":"Successfully looked up CloudConfig","time":"2021-0}
{"IsTestKubeClient":"false","SOURCE":"file[connector.go:73] func[connector.(*Connector).GetClient]","level":"info","msg":"GetClient .. start","time":"2021-04-14T07:22:56.394668482Z"}
{"SOURCE":"file[cluster.go:77] func[db.unmarshal]","level":"info","msg":"DB values is nil","time":"2021-04-14T07:22:56.395376743Z"}
{"SOURCE":"file[context.go:845] func[context.applyFnComApp.func1.1]","appName":"aic-intnet","cluster":"provider1+cluster1","error":"Get kubeconfig failed","level":"error","msg":"Error in creating kubeconfig clie}

test scenario 2
- Logical cloud deployed with namespace: <none>
- Logical cloud was succesfuly instatntited. No namespace was created on target k8s. The cloudconfig table in DB does not have it like you said. But of course there is level: 0 and namespace "deafult"
- Instantiation fials as EMCO can't find the proper cluster configuration when searchng for it in DB: "CloudConfig for this app will be looked up using level and namespace specified","namespace":""


{"SOURCE":"file[appcontext.go:488] func[appcontext.(*AppContext).GetAppInstruction]","level":"info","msg":"Getting app instruction","s":"/context/4605899694760069064/app/instruction/order/","time":"2021-04-14T08}
{"SOURCE":"file[context.go:800] func[context.applyFnComApp]","appsorder":"{\"apporder\":[\"aic-pvc\",\"aic-intnet\",\"aic-vdu\"]}","level":"info","msg":"appsorder ","string":{"apporder":["aic-pvc","aic-intnet","}
{"SOURCE":"file[context.go:817] func[context.applyFnComApp]","fields.level":"1","level":"info","msg":"CloudConfig for this app will be looked up using level and namespace specified","namespace":"","time":"2021-0}
{".Cluster":"cluster1",".Level":"0",".Namespace":"",".Provider":"provider1","SOURCE":"file[connector.go:58] func[connector.GetKubeConfig]","level":"info","msg":"Successfully looked up CloudConfig","time":"2021-0}
{"IsTestKubeClient":"false","SOURCE":"file[connector.go:73] func[connector.(*Connector).GetClient]","level":"info","msg":"GetClient .. start","time":"2021-04-14T08:10:36.327042729Z"}
{"SOURCE":"file[cluster.go:77] func[db.unmarshal]","level":"info","msg":"DB values is nil","time":"2021-04-14T08:10:36.32970619Z"}
{"SOURCE":"file[context.go:845] func[context.applyFnComApp.func1.1]","appName":"aic-intnet","cluster":"provider1+cluster1","error":"Get kubeconfig failed","level":"error","msg":"Error in creating kubeconfig clie}
{".Cluster":"cluster1",".Level":"0",".Namespace":"",".Provider":"provider1","SOURCE":"file[connector.go:58] func[connector.GetKubeConfig]","level":"info","msg":"Successfully looked up CloudConfig","time":"2021-0}
{"IsTestKubeClient":"false","SOURCE":"file[connector.go:73] func[connector.(*Connector).GetClient]","level":"info","msg":"GetClient .. start","time":"2021-04-14T08:10:36.331506813Z"}
{"SOURCE":"file[cluster.go:77] func[db.unmarshal]","level":"info","msg":"DB values is nil","time":"2021-04-14T08:10:36.333477561Z"}


And again if I modify cloudconfig entry in the mongo DB with correct data everything is working fine

**Comment by igordcard** [comment]
Can you share rsync and dcm logs from the instantiation of the logical cloud?
And also the definition of your deployment intent group yaml?
Thanks,

**Comment by herrfox** [comment]
Hi,

Files attached.
[dcm.log](https://github.com/open-ness/EMCO/files/6318809/dcm.log)
[rsync.log](https://github.com/open-ness/EMCO/files/6318810/rsync.log)
[test-app.txt](https://github.com/open-ness/EMCO/files/6318837/test-app.txt)

Regards
Greg

**Comment by igordcard** [comment]
Hi Greg,

Anything in the logs between 14:24:50 and 14:25:07?

I see that there is no logical cloud instantiation section in your test-app.txt yaml - I assume you just forgot to include it. If not, it's necessary that the logical cloud be explicitly instantiated (before instantiating the DIG).

Also, are you feeding the entire test-app.txt to emcoctl all at once? I recommend you run a first patch until the logical cloud instantiation. And then have a second batch that creates everything else and instantiates the DIG (line 227 of yout test-app.txt and below).

**Comment by herrfox** [comment]
Hi,
Sorry for the late reply but unfortunately I spent last months on recovery from serious accident.
Anyway to reply your question: I did instantiate the logical cloud after uploading the test-app.txt but didn't attach it.
it looks like this:

---
#instantiate logical cloud
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/logical-clouds/{{.LogicalCloud}}/instantiate

However as you said I uploaded test-app as a whole file.
I'll try define controller and cloud in one yaml and the app itself in the second one.
As soon as I have the results I will send it.
Regards
Greg

**Comment by herrfox** [comment]
Hi,
Here are the logs and files
[dcm.log](https://github.com/open-ness/EMCO/files/6802267/dcm.log)
[rsync.log](https://github.com/open-ness/EMCO/files/6802382/rsync.log)
[create-cloud.log](https://github.com/open-ness/EMCO/files/6802281/create-cloud.log)

I created cloud and controller
[test-app.yaml.txt](https://github.com/open-ness/EMCO/files/6802314/test-app.yaml.txt)
And send instantiate command. All is PASS.

Hovever if you look into rsync log you can clearly see the configuration contain level 0 and namespace default.
"CloudConfig for this app will be looked up using level and namespace specified","namespace":"default","time":"2021-07-12T14:32:14.717595253Z"}
{".Cluster":"cluster1",".Level":"0",".Namespace":"",".Provider":"provider1","SOURCE":"file[connector.go:58] func[connector.GetKubeConfig]","level":"info","msg":"Successfully looked up CloudConfig","time":"2021-07-12T14:32:14.723387805Z"}

After instantiation of the test app the result is the same as I stated in previous posts.
Regards
Greg

**Comment by igordcard** [comment]
Hi @herrfox,
Can you add "- resourcebundlestates" to the list of resources under the logical cloud and also deploy the latest version of EMCO?
Keep in mind that the API has slightly changed. User permissions for the logical cloud should now be specified in a separate endpoint. See the following as an example: https://github.com/open-ness/EMCO/blob/main/src/tools/emcoctl/examples/l1/2clusters/1-logical-cloud-prerequisites.yaml#L82-L105

**Comment by herrfox** [comment]
I close this BUG. I have no resources to proceed with it. I am sorry.
I keep my fingers crossed for EMCO project.
Regards
HerrFox (Greg)
