### ISSUE TITLE
Helm template helpers not working as intended

### ISSUE THREAD

**Issue by BaudouinH** [open-ness/EMCO#7]
Hello, I ran into two different problems with deployments with EMCO, more specifically Helm's template helpers not working as intended.

I deployed the following Bitnami chart: https://github.com/bitnami/charts/tree/master/bitnami/mongodb, which was packaged in another chart, and encountered the two following problems:

- Firstly, some functions used in bitnami .tpl aren't working with EMCO, as they leverage features of Helm 3.2+, like this function: https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function making the instantiation of the DeploymentIntent fail

I encountered this with the Chart version 10.11.0 of the Bitnami chart

It is not a problem on itself, but I haven't found the exact version of Helm currentlu supported by EMCO

- Secondly, for the same chart, I encountered another issue with template helpers, more specifically the following type of code:

```
{{/*
Return the appropriate apiVersion for statefulset.
*/}}
{{- define "common.capabilities.statefulset.apiVersion" -}}
{{- if semverCompare "<1.14-0" (include "common.capabilities.kubeVersion" .) -}}
{{- print "apps/v1beta1" -}}
{{- else -}}
{{- print "apps/v1" -}}
{{- end -}}
{{- end -}}
```

This code query the kubeVersion to render the statefulset's apiVersion
I used a cluster with Kubernetes 1.19, so normally this code should have returned the apiVersion "apps/v1"

However, with EMCO, this function returned "apps/v1beta1", making the deployment of the statefulset fail on the edge cluster, because this apiVersion is deprecated in Kubernetes 1.19

You can find this code here: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl
And it is used here: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml

I encountered this with older versions of the Bitnami chart, like 10.3.3

**Comment by mohanraj1311** [comment]
@BaudouinH : @ritusood 

For issue1: We are actively working on the helm3 support, we plan to release it in few days.

For the issue 2: I tested the mongo helm charts that you mentioned, it does work for us, but i tested in on helm3 as we already moved our development environments to helm3. It might work for helm 2 as well. Pls try after referring to the pic attached. 
It seems that the mongoDB depends on the "[common](https://github.com/bitnami/charts/tree/master/bitnami/common)" charts which lies outside it. So, to get the mongodb deployed independently u need the charts directory inside your mongodb charts. Pls refer to the pic how we structured it, and deployed using EMCO.
![mongoDB](https://user-images.githubusercontent.com/7053218/112683366-ad2d5080-8e2e-11eb-84b2-2eb40eca7cf8.png)

**Comment by BaudouinH** [comment]
@mohanraj1311 Thank your for your feedback !

I wasn't sure that EMCO's current public release supported Helm 3 or only Helm 2. 

For the second issue, when downloading the Helm chart from Docker Hub, the common utilities should be packaged with the mongodb chart. I will test it again when Helm 3 support is released, as it might be related

**Comment by BaudouinH** [comment]
I tried the same Helm charts with the new release of EMCO and it worked as intended ! Helm3 support seems to have fixed it.
